<a href="https://colab.research.google.com/github/georginadd/EMSC2010_major_project/blob/main/EMSC2010_Major_Assignment_u7925896.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EMSC2010 Major Assignment - Investigating the Relationship Between Ocean Temperature and Coral Bleaching in Australian Reefs

# Project Overview
Project title:

**Datasets used (name and source):** Australian Coral Bleaching Multifactor Dataset

Liu, Bailu; Guan, Lei; Foo, Shawna (2026), “Australian Coral Bleaching Multifactor Dataset”, Mendeley Data, V1, doi: 10.17632/57wwr8bvcz.1

**Metadata**:

Australian Coral Bleaching Multifactor Dataset is an analysis-ready tabular dataset of 2,985 quality-controlled coral bleaching observations across Australian reef regions and adjacent seas, spanning 1998–2017. Each record represents a unique 0.05° grid cell and survey month, with geolocation (LAT, LON), time (Year, Month), bleaching severity, and a suite of multi-factor environmental predictors assembled for statistical modelling and benchmarking.

Bleaching outcomes

   Bleaching observations and severity information in this release were sourced from the updated global mass coral bleaching database (Version 2.0) compiled by Virgen-Urcelay & Donner (2023, v2). The original event-level records were subset to the Australian region and then harmonized to the analysis format used here (unique 0.05° grid cell × survey month). Bleaching is provided as an ordinal severity class (Seve2, 0–3) together with a continuous proxy (Seve) mapped to (0,1) for downstream statistical modelling.

Thermal-stress and climate variables

  Using the NOAA Coral Reef Watch (CRW) 5-km CoralTemp v3.1 SST product, we derived multiple thermal-exposure metrics aligned to each survey record, including Degree Heating Weeks (DHW), maximum HotSpot (maxhs), Heating Increase Rate (HIR; daily rate of increase in DHW during the exposure window), and sea-surface temperature anomaly metrics (SSTA, SSTA_SD, SSTA_freq, SSTA_freq_SD).
  Large-scale climate variability is represented by the Oceanic Niño Index (ONI), computed by NOAA CPC from ERSSTv5 as the 3-month running mean SST anomaly in the Niño-3.4 region (5°N–5°S, 170°–120°W).

Optical environment

  To characterize underwater light regime and water clarity, the dataset includes monthly Level-3 MODIS OceanColor composites: photosynthetically available radiation (PAR) and the diffuse attenuation coefficient at 490 nm (Kd₄₉₀).

Cyclone exposure

  Cyclone exposure indicators (cyclone, cyclone_100, cyclone_200) were derived from the Australian Bureau of Meteorology (BoM) best-track database using distance and time windows around each survey record. Following Lugo-Fernández and Gravois (2010), a 200 km radius was used to indicate cyclone impact.

Bathymetry and proximity metrics

  Depth was taken from event records where available; missing values were supplemented using AusBathyTopo (Geoscience Australia, 2017).
  Distance to land (DIST_L) was derived from the NASA OBPG Distance to the Nearest Coastline global grid (based on GMT intermediate coastline) and resampled to 0.05°.
  Given evidence that mangrove-associated environments can mitigate bleaching, distance to mangroves (DIST_M) was computed as distance to the nearest polygon from Global Mangrove Watch v3 (Bunting et al., 2022).

Regional context

  Regional labels are provided via ECOREGION codes and the original site/region field (Site). Near-surface wind is included as an additional environmental covariate.

AIM:


DATA PREPARATION & COLLECTION:

using:


*   time series analysis
*   correlation/regression
*   hypothesis testing
*   bootstrapping

Aims:

Metadata & dataset cleaning info

**Load in and clean dataset**

In [ ]:
import pandas as pd

coral = pd.read_csv("coral_bleaching_multifactor_dataset.csv")

In [ ]:
coral.isnull().sum()
coral.dropna()

,fid,DHW,maxhs,HIR,SSTA,SSTA_SD,SSTA_freq,SSTA_freq_SD,LAT,LON,...,DIST_L,PAR,kd490,ECOREGION,Site,wind,ONI,cyclone_100,cyclone_200,cyclone
1,620,5.337140,2.17,0.242597,2.24839,0.539326,129,42.0465,-18.658700,146.485200,...,0,50.636,0.750,20143,Torres Strait & Great Barrier Reef,3.09635,1.93,0,0,0
6,626,0.445715,1.07,0.111429,1.14724,0.317168,135,40.8670,-20.259600,148.841700,...,0,48.328,0.636,20143,Torres Strait & Great Barrier Reef,4.62524,1.93,0,0,0
7,627,6.812860,1.91,0.101684,2.20207,0.339992,75,26.1701,-24.925000,152.501500,...,2,53.410,1.518,20202,Bundaberg,3.84543,1.93,0,0,0
9,629,5.284290,2.21,0.240195,2.30129,0.492751,146,43.9204,-18.769100,146.630500,...,-1,48.168,0.718,20143,Torres Strait & Great Barrier Reef,4.19190,1.93,0,0,0
14,666,0.294286,1.05,0.147143,1.44484,0.310936,129,41.9580,-20.340000,148.960000,...,1,43.886,0.704,20143,Great Barrier Reef,6.42845,1.44,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2936,35773,7.394280,1.67,0.116643,2.58000,0.788875,122,37.7760,-18.009367,146.146433,...,0,34.032,0.336,20143,Bedarra reef,4.33984,0.30,0,0,0
2941,35852,9.235720,1.87,0.117142,2.68968,0.782725,141,43.1642,-18.569067,146.482017,...,0,31.892,0.998,20143,Palms West reef,4.90142,0.30,0,0,0
2945,35908,7.768570,1.87,0.206352,2.13258,0.863762,121,26.1701,-24.882600,152.490117,...,2,32.056,3.060,20202,"Bundaberg Area, SE Queensland",4.88651,0.30,0,0,0
2947,36302,11.307200,1.72,0.126178,2.71516,0.911274,116,40.9249,-17.162150,146.005750,...,2,27.740,0.710,20143,High West reef,9.19830,0.31,0,0,0
2948,36320,6.364290,1.52,0.106370,2.26903,0.728712,155,44.4458,-20.471900,149.037150,...,1,26.864,0.620,20143,Seaforth reef,8.23358,0.31,0,0,0

In [ ]:
!pip install bambi #system command to install bambi package

# Import required packages for data handling, plotting, modelling, and model comparison

import numpy as np
import matplotlib.pyplot as plt
import bambi as bmb
import arviz as az
import pandas as pd

Collecting bambi
  Downloading bambi-0.18.0-py3-none-any.whl.metadata (9.0 kB)
Collecting arviz_plots<2.0.0,>=1.0.0 (from bambi)
  Downloading arviz_plots-1.1.0-py3-none-any.whl.metadata (6.7 kB)
Collecting formulae<0.7.0,>=0.6.0 (from bambi)
  Downloading formulae-0.6.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from bambi) (0.21)
Requirement already satisfied: matplotlib>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from bambi) (3.10.0)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bambi) (2.2.2)
Collecting pytensor<4.0.0,>=3.0.0 (from bambi)
  Downloading pytensor-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting pymc<7.0.0,>=6.0.0 (from bambi)
  Downloading pymc-6.0.1-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: seaborn<0.14,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from bambi) (0.13.2)
Collecting sparse<0.18,>=0.17.0 (from bambi)
  Downloading sparse-0.17.0-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting arviz-base<1.2,>=1.1 (from arviz_plots<2.0.0,>=1.0.0->bambi)
  Downloading arviz_base-1.1.0-py3-none-any.whl.metadata (6.6 kB)
Collecting arviz-stats<1.2,>=1.1 (from arviz-stats[xarray]<1.2,>=1.1->arviz_plots<2.0.0,>=1.0.0->bambi)
  Downloading arviz_stats-1.1.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.12/dist-packages (from formulae<0.7.0,>=0.6.0->bambi) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from formulae<0.7.0,>=0.6.0->bambi) (26.2)
Requirement already satisfied: scipy>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from formulae<0.7.0,>=0.6.0->bambi) (1.16.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->bambi) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->bambi) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->bambi) (2026.2)
Collecting arviz<2.0,>=1.1.0 (from pymc<7.0.0,>=6.0.0->bambi)
  Downloading arviz-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: cachetools<7,>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from pymc<7.0.0,>=6.0.0->bambi) (6.2.6)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from pymc<7.0.0,>=6.0.0->bambi) (3.1.2)
Requirement already satisfied: rich>=13.7.1 in /usr/local/lib/python3.12/dist-packages (from pymc<7.0.0,>=6.0.0->bambi) (13.9.4)
Requirement already satisfied: threadpoolctl<4.0.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pymc<7.0.0,>=6.0.0->bambi) (3.6.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.12/dist-packages (from pymc<7.0.0,>=6.0.0->bambi) (4.15.0)
Requirement already satisfied: setuptools>=59.0.0 in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (75.2.0)
Requirement already satisfied: numba<=0.65.1,>=0.58 in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (0.60.0)
Requirement already satisfied: filelock>=3.15 in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (3.29.0)
Requirement already satisfied: etuples in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (0.3.10)
Requirement already satisfied: logical-unification in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (0.4.7)
Requirement already satisfied: miniKanren in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (1.0.5)
Requirement already satisfied: cons in /usr/local/lib/python3.12/dist-packages (from pytensor<4.0.0,>=3.0.0->bambi) (0.4.7)
Requirement already satisfied: xarray>=2024.11.0 in /usr/local/lib/python3.12/dist-packages (from arviz-base<1.2,>=1.1->arviz_plots<2.0.0,>=1.0.0->bambi) (2025.12.0)
Requirement already satisfied: lazy_loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from arviz-base<1.2,>=1.1->arviz_plots<2.0.0,>=1.0.0->bambi) (0.5)
Requirement already satisfied: xarray-einstats in /usr/local/lib/python3.12/dist-packages (from arviz-stats[xarray]<1.2,>=1.1->arviz_plots<2.0.0,>=1.0.0->bambi) (0.10.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<=0.65.1,>=0.58->pytensor<4.0.0,>=3.0.0->bambi) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.9.0->bambi) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.7.1->pymc<7.0.0,>=6.0.0->bambi) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.7.1->pymc<7.0.0,>=6.0.0->bambi) (2.20.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.12/dist-packages (from logical-unification->pytensor<4.0.0,>=3.0.0->bambi) (0.12.1)
Requirement already satisfied: multipledispatch in /usr/local/lib/python3.12/dist-packages (from logical-unification->pytensor<4.0.0,>=3.0.0->bambi) (1.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.7.1->pymc<7.0.0,>=6.0.0->bambi) (0.1.2)
Downloading bambi-0.18.0-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 4.7 MB/s eta 0:00:00
Downloading arviz_plots-1.1.0-py3-none-any.whl (237 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.8/237.8 kB 5.5 MB/s eta 0:00:00
Downloading formulae-0.6.2-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 2.0 MB/s eta 0:00:00
Downloading pymc-6.0.1-py3-none-any.whl (584 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 584.2/584.2 kB 19.8 MB/s eta 0:00:00
Downloading pytensor-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 19.7 MB/s eta 0:00:00
Downloading sparse-0.17.0-py2.py3-none-any.whl (259 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.4/259.4 kB 7.6 MB/s eta 0:00:00
Downloading arviz-1.1.0-py3-none-any.whl (9.2 kB)
Downloading arviz_base-1.1.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 29.2 MB/s eta 0:00:00
Downloading arviz_stats-1.1.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.9/179.9 kB 6.3 MB/s eta 0:00:00
Installing collected packages: sparse, arviz-stats, formulae, arviz-base, pytensor, arviz_plots, arviz, pymc, bambi
  Attempting uninstall: pytensor
    Found existing installation: pytensor 2.38.3
    Uninstalling pytensor-2.38.3:
      Successfully uninstalled pytensor-2.38.3
  Attempting uninstall: arviz
    Found existing installation: arviz 0.22.0
    Uninstalling arviz-0.22.0:
      Successfully uninstalled arviz-0.22.0
  Attempting uninstall: pymc
    Found existing installation: pymc 5.28.5
    Uninstalling pymc-5.28.5:
      Successfully uninstalled pymc-5.28.5
Successfully installed arviz-1.1.0 arviz-base-1.1.0 arviz-stats-1.1.0 arviz_plots-1.1.0 bambi-0.18.0 formulae-0.6.2 pymc-6.0.1 pytensor-3.0.3 sparse-0.17.0

In [ ]:
coral.head()

,fid,DHW,maxhs,HIR,SSTA,SSTA_SD,SSTA_freq,SSTA_freq_SD,LAT,LON,...,DIST_L,PAR,kd490,ECOREGION,Site,wind,ONI,cyclone_100,cyclone_200,cyclone
0,619,3.488580,1.880000,0.183609,2.00000,0.419631,154,47.9862,-18.7502,147.2688,...,54,51.558,0.590,20143,Torres Strait & Great Barrier Reef,5.16486,1.93,0,0,0
1,620,5.337140,2.170000,0.242597,2.24839,0.539326,129,42.0465,-18.6587,146.4852,...,0,50.636,0.750,20143,Torres Strait & Great Barrier Reef,3.09635,1.93,0,0,0
2,621,1.587140,1.250000,0.079357,1.37742,0.347459,132,47.0726,-17.2661,146.3636,...,34,45.124,0.540,20143,Torres Strait & Great Barrier Reef,4.72417,1.93,0,0,0
3,622,1.768570,1.320000,0.093083,1.39517,0.333901,156,47.5125,-17.8847,146.5938,...,44,48.398,0.838,20143,Torres Strait & Great Barrier Reef,4.73477,1.93,0,0,0
4,623,0.144286,0.980001,0.144286,1.05862,0.367917,112,48.1280,-16.7601,147.7259,...,184,56.630,0.276,20150,Torres Strait & Great Barrier Reef,5.59268,1.93,0,0,0

In [ ]:
# Count how many observations are available for each reef

coral["Site"].value_counts()

Site
Great Barrier Reef                    842
Torres Strait & Great Barrier Reef    801
U/N Reef                              173
Coral Sea                              46
Torres Strait                          30
                                     ...
Sykes Reef                              1
One Tree Island Reef                    1
Mast Head Reef                          1
Heron Reef                              1
Wreck Island Reef                       1
Name: count, Length: 646, dtype: int64